server:
  port: 8088
  tomcat:
    max-threads: 200
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weiapp?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 111708@ss.com
mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl